variables:
  TF_GLOBAL_OPTIONS: -chdir=infrastructure

stages:
  # - build
  - test

test-api:
  stage: test
  image: python:3
  script:
    - cd api
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: api/coverage.xml