variables:
  TF_GLOBAL_OPTIONS: -chdir=infrastructure

stages:
  - build
  - test

test-api:
  stage: test
  image: python:3
  script:
    - cd api
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    - pytest --cov --cov-report term --cov-report xml:coverage.xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: api/coverage.xml
  
build-web-app:
  stage: build
  image: node:latest
  script:
    - cd app
    - yarn
  cache:
    paths:
      - app/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - app/node_modules/

test-web-app:
  stage: test
  image: node:latest
  # coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  script:
    - cd app
    - yarn test:coverage
  artifacts:
    when: always
    reports:
      junit:
        - app/coverage/cobertura-coverage.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml