- name: Inspiring text server setup
  hosts: all
  remote_user: root
  become: true

  tasks:
    - name: Install Aptitude via apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes
    
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Copy file with owner and permissions for api
      ansible.builtin.copy:
        src: ./api
        dest: /www/var/inspiring-text/api 

    - name: Build the Docker image app
      command: docker build -t inspiring-text-api /www/var/inspiring-text/api

    - name: Run the Docker container to display the public SSH key
      command: docker run --rm inspiring-text-api
      # register: run_output

    # - name: Copy file with owner and permissions for app
    #   ansible.builtin.copy:
    #     src: ./api
    #     dest: /www/var/inspiring-text/api 